### ISSUE TITLE
Jellyfin 10.9.0 (unstable) - Plugin Data Dashboard is empty

### ISSUE THREAD

**Issue by Cebrain** [jellyfin/jellyfin-plugin-playbackreporting#75]
Hi,

i am testing the jellyfin server 10.9.0 in unstable version and the plugin is not displaying any history.
I couldnt find any useful logs for the moment.

I know it is an unstable jellyfin version but when stable  is released, maybe it can already fixed beforehand?

**Comment by cesarblancg** [comment]
Same Here!  

`[2023-05-26 09:23:24.806 +02:00] [ERR] [42] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request. URL "POST" "/user_usage_stats/submit_custom_query".
System.InvalidOperationException: The AuthorizationPolicy named: 'DefaultAuthorization' was not found.
   at Microsoft.AspNetCore.Authorization.AuthorizationPolicy.CombineAsync(IAuthorizationPolicyProvider policyProvider, IEnumerable'1 authorizeData, IEnumerable'1 policies)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Api.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Api.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Api.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Api.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Api.Middleware.ExceptionMiddleware.Invoke(HttpContext context)`

**Comment by rigrig** [comment]
#80 was fixed, so this should be fixed in 13.2403.6.0
