### ISSUE TITLE
System.ArgumentOutOfRangeException: Index was out of range

### ISSUE THREAD

**Issue by Natrinicle** [jellyfin/jellyfin-plugin-playbackreporting#77]
Started getting the following errors every 10 seconds or so in the log output. Running Jellyfin in a Docker container with Nvidia HW Acceleration and have a couple of DLNA media centers on the network which might be related given the last traceback line?

* Jellyfin version: 10.8.11
* Playback Reporting version: 13.0.0.0

```
[16:44:55] [ERR] Error reporting progress
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint.SessionManager_PlaybackProgress(Object sender, PlaybackProgressEventArgs e)
   at Emby.Server.Implementations.Session.SessionManager.OnPlaybackProgress(PlaybackProgressInfo info, Boolean isAutomated)
   at Emby.Dlna.PlayTo.PlayToController.OnDevicePlaybackProgress(Object sender, PlaybackProgressEventArgs e)
```

**Comment by capJavert** [comment]
Got this one randomly as well, not as often 🤞 but something to look into probably.

```
[2024-01-05 14:36:11.802 +01:00] [FTL] [80] Main: Unhandled Exception
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
   at Emby.Server.Implementations.Session.WebSocketController.OnConnectionClosed(Object sender, EventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
```

**Comment by fernvenue** [comment]
Can be reproduced on version 10.9.9.

**Comment by fernvenue** [comment]
Here's the log information from my Jellyfin server:

```
[2024-08-17 21:08:06.139 +06:00] [FTL] [20] Main: Unhandled Exception
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.Remove(T item)
   at Emby.Server.Implementations.Session.WebSocketController.OnConnectionClosed(Object sender, EventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

**Comment by sankukai44** [comment]
HI, I have the same issue, i reinstall jellyfin  from scratch and again, this error ... i need to restart the server everyday now ...

[2024-08-17 17:53:12.279 +02:00] [FTL] [71] Main: Unhandled Exception
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at Emby.Server.Implementations.Session.WebSocketController.OnConnectionClosed(Object sender, EventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
[2024-08-17 20:19:52.427 +02:00] [INF] [1] Main: Jellyfin version: "10.9.9"

**Comment by razor2611** [comment]
Started to happen on mine on version 10.9.11
`[09:57:45] [FTL] [162] Main: Unhandled Exception
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at Emby.Server.Implementations.Session.WebSocketController.OnConnectionClosed(Object sender, EventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()`

**Comment by PeeBeerBeach** [comment]
I have the same trouble. I could boil it down to an invalid proxy entry (being '[::ffff:172.17.0.1]').
I got rid of it in the network.xml settings and now it starts again.

Here is the log from back then:



```
Unhandled exception. System.ArgumentOutOfRangeException: The prefix length was out of range. (Parameter 'prefixLength')
   at Microsoft.AspNetCore.HttpOverrides.IPNetwork..ctor(IPAddress prefix, Int32 prefixLength, Boolean checkPrefixLengthRange)
   at Jellyfin.Server.Extensions.ApiServiceCollectionExtensions.AddIPAddress(NetworkConfiguration config, ForwardedHeadersOptions options, IPAddress addr, Int32 prefixLength)
   at Jellyfin.Server.Extensions.ApiServiceCollectionExtensions.AddProxyAddresses(NetworkConfiguration config, String[] allowedProxies, ForwardedHeadersOptions options)
   at Jellyfin.Server.Extensions.ApiServiceCollectionExtensions.ConfigureForwardHeaders(NetworkConfiguration config, ForwardedHeadersOptions options)
   at Jellyfin.Server.ServerSetupApp.SetupServer.<>c__DisplayClass19_0.<RunAsync>b__4(ForwardedHeadersOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.UnnamedOptionsManager`1.get_Value()
   at Microsoft.AspNetCore.HttpOverrides.ForwardedHeadersMiddleware..ctor(RequestDelegate next, ILoggerFactory loggerFactory, IOptions`1 options)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.ConstructorInvoker.InvokeDirectByRefWithFewArgs(Span`1 copyOfArgs)
   at System.Reflection.ConstructorInvoker.InvokeDirectByRef(Object arg1, Object arg2, Object arg3, Object arg4)
   at System.Reflection.ConstructorInvoker.InvokeImpl(Object arg1, Object arg2, Object arg3, Object arg4)
   at System.Reflection.ConstructorInvoker.Invoke(Span`1 arguments)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.ReflectionMiddlewareBinder.CreateMiddleware(RequestDelegate next)
   at Microsoft.AspNetCore.Builder.ApplicationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__14_1(IHostedService service, CancellationToken token)
   at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Jellyfin.Server.ServerSetupApp.SetupServer.RunAsync()
   at Jellyfin.Server.Program.StartApp(StartupOptions options) 
   at Jellyfin.Server.Program.<Main>(String[] args)

```
