### ISSUE TITLE
Restart action from admin dashboard fails with 'database is locked'

### ISSUE THREAD

**Issue by Terrance** [jellyfin/jellyfin-plugin-playbackreporting#96]
Triggering a Jellyfin server restart in the UI (via the admin dashboard) leads to a crash where the database is locked, presumably because something hasn't released it during the restart.

<details>
<summary>Jellyfin logs</summary>

```
[11:07:07] [INF] Sending shutdown notifications
[11:07:07] [INF] WS 172.16.2.1 closed
[11:07:07] [INF] Stopping NAT discovery
[11:07:07] [INF] Disposing SsdpDevicePublisher
[11:07:07] [INF] Disposing PlayToManager
[11:07:07] [INF] Running query planner optimizations in the database... This might take a while
[11:07:07] [INF] SsdpCommunicationsServer disposing _BroadcastListenSocket
[11:07:07] [INF] SsdpCommunicationsServer Disposing 1 sendSockets
[11:07:07] [INF] SsdpCommunicationsServer disposing sendSocket from 172.16.1.1
[11:07:07] [INF] Stopping directory watching for path ...
[11:07:08] [INF] Disposing CoreAppHost
[11:07:08] [INF] Disposing MusicBrainzArtistProvider
[11:07:08] [INF] Disposing MusicBrainzAlbumProvider
[11:07:08] [INF] Disposing PluginManager
[11:07:08] [INF] Setting cache path: /var/cache/jellyfin
[11:07:08] [INF] Loading assemblies
[11:07:08] [INF] Loaded assembly Jellyfin.Plugin.Bookshelf, Version=12.0.0.0, Culture=neutral, PublicKeyToken=null from /var/lib/jellyfin/plugins/Bookshelf_12.0.0.0/Jellyfin.Plugin.Bookshelf.dll
[11:07:08] [INF] Loaded assembly SharpCompress, Version=0.38.0.0, Culture=neutral, PublicKeyToken=afb0a02973931d96 from /var/lib/jellyfin/plugins/Bookshelf_12.0.0.0/SharpCompress.dll
[11:07:08] [INF] Loaded assembly ZstdSharp, Version=0.8.1.0, Culture=neutral, PublicKeyToken=8d151af33a4ad5cf from /var/lib/jellyfin/plugins/Bookshelf_12.0.0.0/ZstdSharp.dll
[11:07:08] [INF] Loaded assembly Jellyfin.Plugin.Dlna.Model, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null from /var/lib/jellyfin/plugins/DLNA_5.0.0.0/Jellyfin.Plugin.Dlna.Model.dll
[11:07:08] [INF] Loaded assembly Rssdp, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null from /var/lib/jellyfin/plugins/DLNA_5.0.0.0/Rssdp.dll
[11:07:08] [INF] Loaded assembly Jellyfin.Plugin.Dlna.Playback, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null from /var/lib/jellyfin/plugins/DLNA_5.0.0.0/Jellyfin.Plugin.Dlna.Playback.dll
[11:07:08] [INF] Loaded assembly Jellyfin.Plugin.Dlna, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null from /var/lib/jellyfin/plugins/DLNA_5.0.0.0/Jellyfin.Plugin.Dlna.dll
[11:07:08] [INF] Skipping disabled plugin 8.1.0.0 of Last.fm
[11:07:08] [INF] Loaded assembly Jellyfin.Plugin.ListenBrainz.Api, Version=5.0.0.2, Culture=neutral, PublicKeyToken=null from /var/lib/jellyfin/plugins/ListenBrainz_5.0.0.2/Jellyfin.Plugin.ListenBrainz.Api.dll
[11:07:08] [INF] Loaded assembly Jellyfin.Plugin.ListenBrainz, Version=5.0.0.2, Culture=neutral, PublicKeyToken=null from /var/lib/jellyfin/plugins/ListenBrainz_5.0.0.2/Jellyfin.Plugin.ListenBrainz.dll
[11:07:08] [INF] Loaded assembly Jellyfin.Plugin.ListenBrainz.Http, Version=5.0.0.2, Culture=neutral, PublicKeyToken=null from /var/lib/jellyfin/plugins/ListenBrainz_5.0.0.2/Jellyfin.Plugin.ListenBrainz.Http.dll
[11:07:08] [INF] Loaded assembly Jellyfin.Plugin.ListenBrainz.MusicBrainzApi, Version=5.0.0.2, Culture=neutral, PublicKeyToken=null from /var/lib/jellyfin/plugins/ListenBrainz_5.0.0.2/Jellyfin.Plugin.ListenBrainz.MusicBrainzApi.dll
[11:07:08] [INF] Loaded assembly Jellyfin.Plugin.ListenBrainz.Common, Version=5.0.0.2, Culture=neutral, PublicKeyToken=null from /var/lib/jellyfin/plugins/ListenBrainz_5.0.0.2/Jellyfin.Plugin.ListenBrainz.Common.dll
[11:07:08] [INF] Loaded assembly Jellyfin.Plugin.OpenSubtitles, Version=20.0.0.0, Culture=neutral, PublicKeyToken=null from /var/lib/jellyfin/plugins/Open Subtitles_20.0.0.0/Jellyfin.Plugin.OpenSubtitles.dll
[11:07:08] [INF] Loaded assembly SQLitePCL.pretty, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null from /var/lib/jellyfin/plugins/Playback Reporting_15.0.0.0/SQLitePCL.pretty.dll
[11:07:08] [INF] Loaded assembly Jellyfin.Plugin.PlaybackReporting, Version=15.0.0.0, Culture=neutral, PublicKeyToken=null from /var/lib/jellyfin/plugins/Playback Reporting_15.0.0.0/Jellyfin.Plugin.PlaybackReporting.dll
[11:07:08] [INF] Loaded assembly System.IO.Packaging, Version=4.0.5.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a from /var/lib/jellyfin/plugins/Reports_17.0.0.0/System.IO.Packaging.dll
[11:07:08] [INF] Loaded assembly SixLabors.Fonts, Version=1.0.0.0, Culture=neutral, PublicKeyToken=d998eea7b14cab13 from /var/lib/jellyfin/plugins/Reports_17.0.0.0/SixLabors.Fonts.dll
[11:07:08] [INF] Loaded assembly ExcelNumberFormat, Version=1.1.0.0, Culture=neutral, PublicKeyToken=23c6f5d73be07eca from /var/lib/jellyfin/plugins/Reports_17.0.0.0/ExcelNumberFormat.dll
[11:07:08] [INF] Loaded assembly Jellyfin.Plugin.Reports, Version=17.0.0.0, Culture=neutral, PublicKeyToken=null from /var/lib/jellyfin/plugins/Reports_17.0.0.0/Jellyfin.Plugin.Reports.dll
[11:07:08] [INF] Loaded assembly ClosedXML, Version=0.97.0.0, Culture=neutral, PublicKeyToken=fd1eb21b62ae805b from /var/lib/jellyfin/plugins/Reports_17.0.0.0/ClosedXML.dll
[11:07:08] [INF] Loaded assembly DocumentFormat.OpenXml, Version=2.16.0.0, Culture=neutral, PublicKeyToken=8fb06cb64d019a17 from /var/lib/jellyfin/plugins/Reports_17.0.0.0/DocumentFormat.OpenXml.dll
[11:07:08] [INF] Loaded assembly Jellyfin.Plugin.TMDbBoxSets, Version=11.0.0.0, Culture=neutral, PublicKeyToken=null from /var/lib/jellyfin/plugins/TMDb Box Sets_11.0.0.0/Jellyfin.Plugin.TMDbBoxSets.dll
[11:07:08] [INF] Loaded assembly Trakt, Version=26.0.0.0, Culture=neutral, PublicKeyToken=null from /var/lib/jellyfin/plugins/Trakt_26.0.0.0/Trakt.dll
[11:07:08] [INF] Loaded assembly Handlebars, Version=2.1.6.0, Culture=neutral, PublicKeyToken=22225d0bf33cd661 from /var/lib/jellyfin/plugins/Webhook_15.0.0.0/Handlebars.dll
[11:07:08] [INF] Loaded assembly BouncyCastle.Cryptography, Version=2.0.0.0, Culture=neutral, PublicKeyToken=072edcf4a5328938 from /var/lib/jellyfin/plugins/Webhook_15.0.0.0/BouncyCastle.Cryptography.dll
[11:07:08] [INF] Loaded assembly MailKit, Version=4.7.0.0, Culture=neutral, PublicKeyToken=4e064fe7c44a8f1b from /var/lib/jellyfin/plugins/Webhook_15.0.0.0/MailKit.dll
[11:07:08] [INF] Loaded assembly MimeKit, Version=4.7.0.0, Culture=neutral, PublicKeyToken=bede1c8a46c66814 from /var/lib/jellyfin/plugins/Webhook_15.0.0.0/MimeKit.dll
[11:07:08] [INF] Loaded assembly MQTTnet.Extensions.ManagedClient, Version=4.3.6.1152, Culture=neutral, PublicKeyToken=fdb7629f2e364a63 from /var/lib/jellyfin/plugins/Webhook_15.0.0.0/MQTTnet.Extensions.ManagedClient.dll
[11:07:08] [INF] Loaded assembly Jellyfin.Plugin.Webhook, Version=15.0.0.0, Culture=neutral, PublicKeyToken=null from /var/lib/jellyfin/plugins/Webhook_15.0.0.0/Jellyfin.Plugin.Webhook.dll
[11:07:08] [INF] Loaded assembly MQTTnet, Version=4.3.6.1152, Culture=neutral, PublicKeyToken=fdb7629f2e364a63 from /var/lib/jellyfin/plugins/Webhook_15.0.0.0/MQTTnet.dll
[11:07:08] [INF] Defined LAN subnets: ["172.16.0.0/16", ...]
[11:07:08] [INF] Defined LAN exclusions: []
[11:07:08] [INF] Used LAN subnets: ["172.16.0.0/16", ...]
[11:07:08] [INF] Filtered interface addresses: ["127.0.0.1", "172.16.1.1", ...]
[11:07:08] [INF] Bind Addresses ["::"]
[11:07:08] [INF] Remote IP filter is Allowlist
[11:07:08] [INF] Filtered subnets: []
[11:07:08] [FTL] Error while starting server
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 8: 'attempt to write a readonly database'.
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Emby.Server.Implementations.Data.SqliteExtensions.Execute(SqliteConnection sqliteConnection, String commandText)
   at Emby.Server.Implementations.Data.ManagedConnection.Execute(String commandText)
   at Emby.Server.Implementations.Data.BaseSqliteRepository.Initialize()
   at Emby.Server.Implementations.Data.SqliteItemRepository.Initialize()
   at Emby.Server.Implementations.ApplicationHost.InitializeServices()
   at Jellyfin.Server.Program.StartServer(IServerApplicationPaths appPaths, StartupOptions options, IConfiguration startupConfig)
[11:07:08] [INF] Running query planner optimizations in the database... This might take a while
[11:07:08] [INF] Disposing CoreAppHost
[11:07:08] [INF] Disposing PluginManager
```
</details>

Whilst there isn't anything in the logs to suggest this is down to the Playback Reporting plugin specifically, manually disabling/removing it does appear to allow me to restart normally, and this seems to be a known source of database-related issues (https://github.com/jellyfin/jellyfin/issues/13058#issuecomment-2481378365).

**Comment by a-mnich** [comment]
duplicate of #89  
A fix will be included in the upcoming release #100

**Comment by chenks** [comment]
> duplicate of [#89](https://github.com/jellyfin/jellyfin-plugin-playbackreporting/issues/89) A fix will be included in the upcoming release [#100](https://github.com/jellyfin/jellyfin-plugin-playbackreporting/pull/100)

sadly it wasn't fixed.

**Comment by yeathn** [comment]
+1

**Comment by Avamander** [comment]
I deleted all the previous plugin versions, no dice. The database still locks and Jellyfin starts to consume a lot of CPU.

**Comment by chenks** [comment]
Maybe delete and reinstall the currently installed version. 

The problem no longer exists for me

**Comment by Terrance** [comment]
I uninstalled this plugin a while ago to restore service; having now just installed 16.0.0.0 afresh, the Restart button is again broken.  I've confirmed there's no other versions lying around in the plugins directory.

**Comment by chenks** [comment]
Not sure what to tell you then, as the restart button is working correctly. 

Does the issue go away if you remove the plugin?

**Comment by yeathn** [comment]
I also deleted all old folders and still have the same issue. Im on a Proxmox LXC with https://community-scripts.github.io/ProxmoxVE/scripts?id=jellyfin

**Comment by chenks** [comment]
> I also deleted all old folders and still have the same issue. Im on a Proxmox LXC with https://community-scripts.github.io/ProxmoxVE/scripts?id=jellyfin

also using a proxmox LXC (with the same jellyfin script), and restarts works fine with only v16.x plugin present.
there has to be something else causing the problem.

**Comment by a-mnich** [comment]
The update initially completely solved the issue for me. I tested the new verision for over two months before it was released, but recently the issue came back and also occurs now again on every restart.  

I suspect that this has to to with the order in which the plugins are loaded / unloaded. Unfortunately I couldn't figure out how to circumvent this issue and what exactely causes it.

**Comment by Terrance** [comment]
I had quite a few other plugins enabled so I was guessing the problem may lie between this and another plugin conflicting over database shutdown (disabling just this plugin would fix the problem, so perhaps disabling a single other would too).

However, having disabled all other plugins with a _Disable_ option (the remaining ones being at versions equal to Jellyfin itself so I assume they're built-in) I'm still getting `attempt to write a readonly database`.

For completeness, the plugin state is as follows:

```
[INF] Loading assemblies
[INF] Skipping disabled plugin 12.0.0.0 of Bookshelf
[INF] Skipping disabled plugin 8.0.0.0 of Cover Art Archive
[INF] Skipping disabled plugin 8.0.0.0 of DLNA
[INF] Skipping disabled plugin 8.1.0.0 of Last.fm
[INF] Skipping disabled plugin 5.2.0.4 of ListenBrainz
[INF] Skipping disabled plugin 20.0.0.0 of Open Subtitles
[INF] Loaded assembly SQLitePCL.pretty, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null from /var/lib/jellyfin/plugins/Playback Reporting_16.0.0.0/SQLitePCL.pretty.dll
[INF] Loaded assembly Jellyfin.Plugin.PlaybackReporting, Version=16.0.0.0, Culture=neutral, PublicKeyToken=null from /var/lib/jellyfin/plugins/Playback Reporting_16.0.0.0/Jellyfin.Plugin.PlaybackReporting.dll
[INF] Skipping disabled plugin 17.0.0.0 of Reports
[INF] Skipping disabled plugin 11.0.0.0 of TMDb Box Sets
[INF] Skipping disabled plugin 26.0.0.0 of Trakt
[INF] Skipping disabled plugin 17.0.0.0 of Webhook
...
[INF] Loaded plugin: Playback Reporting 16.0.0.0
[INF] Loaded plugin: TMDb 10.10.7.0
[INF] Loaded plugin: Studio Images 10.10.7.0
[INF] Loaded plugin: OMDb 10.10.7.0
[INF] Loaded plugin: MusicBrainz 10.10.7.0
[INF] Loaded plugin: AudioDB 10.10.7.0
[INF] Kestrel is listening on all interfaces
[INF] EventMonitorEntryPoint Running
[INF] Sqlite version: 3.41.2
```

**Comment by a-mnich** [comment]
The issue appears to be resolved for me since updating to Jellyfin`10.11.x`.  
I can now restart the server from the Admin UI without any issues.

**Comment by Terrance** [comment]
Just re-enabled the plugin on Jellyfin 10.11.6, looks like restarts are working again for me too.

**Comment by matteocnt92** [comment]
I just encountered this issue and I had to disable this plugin in order for jellyfin to work again
